examples/DateTest.php, src/Eris/Generator/Date.php, test/Eris/ExampleEnd2EndTest.php, test/Eris/Generator/DateTest.php
It is not clear to me how to shrink dates: bringing them towards 1970 (or the lower limit) does not seem to simplify much.
Another option would be to shrink in detail:
```
"2014-12-22T14:10:34"
"2014-12-22T14:10:00"
"2014-12-22T14:00:00"
"2014-12-22T00:00:00"
"2014-12-01T00:00:00"
"2014-01-01T00:00:00"
"1970-01-01T00:00:00"
```
=> Date generator

examples/ErrorTest.php, src/Eris/Quantifier/ForAll.php, test/Eris/ExampleEnd2EndTest.php
* Fixes https://github.com/giorgiosironi/eris/issues/36 by providing a way for the user to explicitate the input
* Starts the first shot at https://trello.com/c/3OeQFdkx/32-an-user-can-run-a-test-and-see-what-was-the-first-failed-example-and-the-following-shrinking-process as the whole process is very large, but at least the original failing input and the shrinked one are easy to show.
I will also look into an alternative way of passing parameters, different from environment variables.
=> Error messages

src/Eris/Antecedent/IndependentConstraintsAntecedent.php, src/Eris/Antecedent/PrintableCharacter.php, src/Eris/Antecedent/SingleCallbackAntecedent.php, src/Eris/Generator/Boolean.php, src/Eris/Generator/Character.php, src/Eris/Generator/Constant.php, src/Eris/Generator/Date.php, src/Eris/Generator/Elements.php, src/Eris/Generator/Float.php, src/Eris/Generator/Frequency.php, src/Eris/Generator/Integer.php, src/Eris/Generator/Names.php, src/Eris/Generator/Natural.php, src/Eris/Generator/OneOf.php, src/Eris/Generator/Regex.php, src/Eris/Generator/Sequence.php, src/Eris/Generator/String.php, src/Eris/Generator/Tuple.php, src/Eris/Generator/Vector.php, src/Eris/Generator/functions.php, src/Eris/Quantifier/ForAll.php, src/Eris/Shrinker/Random.php, src/Eris/TestTrait.php
There MUST be one blank line after the namespace declaration, and there MUST be one blank line after the block of use declarations.
=> added a blank line according to psr2: 

src/Eris/Generator/Integer.php, test/Eris/Generator/IntegerTest.php
- `nat()` generates an integer in `[0, +oo)`
- `pos()` generates an integer in `[1, +oo)`
- `neg()` generates an integer in `(-oo, -1]`
pos() is particularly useful for amounts of money to use in transactions as they cannot be 0.
=> Consistent mathematical definition of pos(), nat() and neg()

src/Eris/Generator/FloatGenerator.php, src/Eris/Generator/StringGenerator.php, test/Eris/Generator/FloatGeneratorTest.php, test/Eris/Generator/StringGeneratorTest.php
Hi, I renamed `Float` and `String` generators as we discussed in #55. New names are `FloatGenerator` and `StringGenerator`. I ran the tests with this Docker image https://hub.docker.com/_/php/ `php:7.0-cli` and all tests in `test` folder are green.
=> Rename Float and String generators with valid names for PHP 7

.travis.yml, composer.json, examples/IntegerTest.php, examples/SequenceTest.php, examples/SortTest.php, src/Eris/Listener.php, src/Eris/Listener/CollectFrequencies.php, src/Eris/Listener/EmptyListener.php, src/Eris/Quantifier/ForAll.php, src/Eris/TestTrait.php
The main goal of this pull request is to be a little bit less blind on which kind of values have been generated by eris's generators.
Basically we are porting the `eqc:collect/2` (or the `eqc:aggregate/2`) functionality to eris.
The user will be able to set a collection function which will be invoked with the same value of the property evaluation function. The value returned by the "collection function" should uniquely identify the values generated during the property evaluation. So that, at the end of the evaluation we will be able to print some useful information about the distribution of the generated data.
Here are a couple of examples from this spike:
```
39%  []
11%  [0]
5%  [1]
3%  [2]
2%  [0,4,3]
2%  [3]
2%  [2,1]
...
1%  [8,8,5,5]
1%  [9,8,10,7,0,9]
1%  [6,5,10]
1%  [2,2]
1% …
```
=> [RFC] - Generated data distribution

examples/CharacterTest.php, examples/DateTest.php, examples/FrequencyTest.php, examples/RegexTest.php, examples/ShrinkingTest.php, examples/ShrinkingTimeLimitTest.php, src/Eris/TestTrait.php
=> Removing support for array of generators in forAll()

examples/BindTest.php, examples/MapTest.php, src/Eris/Generator/BindGenerator.php, src/Eris/Generator/ConstantGenerator.php, src/Eris/TestTrait.php, test/Eris/Generator/BindGeneratorTest.php
Ported from
https://github.com/clojure/test.check/blob/master/doc/intro.md
Means we can use a random value to build a completely new Generator, instead of just applying a pure function to the output. The example builds an outer Generator which selects a random element from a vector, which cannot be done with `map`.
=> bind() generator

.travis.yml
This PR 
:information_desk_person: Specifically, here's what this suggests
* add vertical whitespace for enhanced legibility
* move sections around and using more appropriate sections
* update composer itself before installing dependencies
* attempt to authenticate with the GitHub API using an environment variable `GITHUB_TOKEN`
* enable caching for dependencies as installed with composer to speed up the build
* disable xdebug as it is not needed, but speeds up the build 
* installing dependencies with `--prefer-dist` to help caching dependencies
@giorgiosironi 
If by any chance you could provide a GitHub token as an environment variable `GITHUB_TOKEN` at https://travis-ci.org/giorgiosironi/eris/settings, that would be great, helps with authenticating against the GitHub API.
=> Fix: Improve Travis configuration

examples/CharacterTest.php, test/Eris/Generator/AssociativeArrayGeneratorTest.php, test/Eris/Generator/BindGeneratorTest.php, test/Eris/Generator/CharacterGeneratorTest.php, test/Eris/Generator/ChooseGeneratorTest.php, test/Eris/Generator/ConstantGeneratorTest.php, test/Eris/Generator/DateGeneratorTest.php, test/Eris/Generator/ElementsGeneratorTest.php, test/Eris/Generator/FloatGeneratorTest.php, test/Eris/Generator/FrequencyGeneratorTest.php, test/Eris/Generator/IntegerGeneratorTest.php, test/Eris/Generator/MapGeneratorTest.php, test/Eris/Generator/OneOfGeneratorTest.php, test/Eris/Generator/RegexGeneratorTest.php, test/Eris/Generator/SequenceGeneratorTest.php, test/Eris/Generator/SetGeneratorTest.php, test/Eris/Generator/SubsetGeneratorTest.php, test/Eris/Generator/SuchThatGeneratorTest.php, test/Eris/Generator/TupleGeneratorTest.php, test/Eris/Generator/VectorGeneratorTest.php, test/Eris/Listener/LogTest.php, test/Eris/Quantifier/TimeBasedTerminationConditionTest.php
This PR
:information_desk_person: This is the visibility as defined on the the parent, no need to increase it.
=> Fix: Reduce visibility of setUp()

composer.json
This PR
Related to #77.
Alternative to #76.
=> Fix: Specify namespace prefix for PSR-0 autoloading

test/Eris/ExampleEnd2EndTest.php, test/Eris/Generator/GeneratedValueTest.php
This PR
:information_desk_person: For reference, see [`PHPUnit_Framework_Assert::assertRegExp()`](https://github.com/sebastianbergmann/phpunit/blob/b5f314f4c43b22ccdeb68890ec4213b8b3465eb9/src/Framework/Assert.php#L1482).
=> Fix: Case-insensitive method calls

.travis.yml
This PR
:information_desk_person: This helps spotting issues with `composer.son`. For reference, see https://getcomposer.org/doc/03-cli.md#validate.
Running this on current `master`:
```
$ composer validate
./composer.json is valid, but with a few warnings
See https://getcomposer.org/doc/04-schema.md for details on the schema
Defining autoload.psr-0 with an empty namespace prefix is a bad idea for performance
```
=> Fix: Validate composer.json on Travis

composer.json
This PR
:information_desk_person: This would come in handy, too, if we want to start using `php-cs-fixer`!
Run
```
$ composer test
```
to run all the things.
=> Enhancement: Add Composer script for simplifying running tests locally

src/Eris/Generator/AssociativeArrayGenerator.php, src/Eris/Generator/FrequencyGenerator.php, src/Eris/Generator/TupleGenerator.php, src/Eris/Listener/Log.php, src/Eris/Quantifier/Evaluation.php, src/Eris/Quantifier/TimeBasedTerminationCondition.php
=> Fix: Declare fields otherwise declared dynamically

docs/generators/composite.rst, examples/SuchThatTest.php, src/Eris/Generator/SuchThatGenerator.php, test/Eris/ExampleEnd2EndTest.php, test/Eris/Generator/SuchThatGeneratorTest.php
With this change we support PHPUnit constraints in suchThat().
However now there are two duplicate functionalities:
- `suchThat()` Generator (https://github.com/giorgiosironi/eris/blob/master/examples/SuchThatTest.php)
- `when()` call on objects returned by `forAll()` (https://github.com/giorgiosironi/eris/blob/master/examples/WhenTest.php)
both supporting callables and PHPUnit constraints.
Given that `suchThat()` has more power, as its filtering result can be passed to other Generators. So I propose to either:
- remove `when()`
- implement `when()` in terms of `suchThat()`, by wrapping the Generators in a `tuple()`; keeps backward compatibility. Unsure whether to document `when()` and officially support it or not.
=> when() and suchThat() unification

src/PHPUnitCommand.php, src/TestTrait.php, test/PHPUnitCommandTest.php
`--filter` with single backslashes doesn't work properly
=> Escape backslashes in "Reproduce with:"

src/PHPUnitCommand.php, test/PHPUnitCommandTest.php
This is a follow up of #85 since I noticed that using backslash is not enough
=> Use single quote when filtering by name

ChangeLog.md, examples/SuchThatTest.php, src/Generator/SkipValueException.php, src/Generator/SuchThatGenerator.php, src/Quantifier/ForAll.php, test/Generator/SuchThatGeneratorTest.php
If after `$this->maximumAttempts` attempts SuchThatGenerator cannot
produce a good value, it should throw a special exception recognized by
ForAll. ForAll will skip this iteration and go on with a larger size
rather than continuing to use `$size = 0` which may produce always the
same value (then discarded).
=> Closes #100: suchThat() should not get stuck on a small size

README.md
Strictly speaking it is not wrong, as the example does not reside in a namespace.
However normally tests do reside in a namespace, so copying the example will
result in an error unless this is modified in most cases.
=> Add missing backflash

examples/CharacterTest.php
Travis' HHVM doesn't seem to like aliased use statements, so this removes them from the only example test that uses them.
Of course if this fails to build I'll drop this hack.
=> Fix Travis' build on HHVM

examples/generating_integers.php
Somewhere in the development leading up to PHP 7.2, `var_dump()` started outputting the file and line number as part of it's output. This causes one of the end-to-end tests to fail as the example script it uses outputs twice as many lines as expected.
This fixes this by using `var_export()` and a little wrapping to output useful debug data if something goes wrong and sensible output otherwise.
=> Update example to output a single line on PHP 7.2

.travis.yml, examples/LimitToTest.php, examples/ShrinkingTest.php
Hi @giorgiosironi,
this PR is intended to be a fix to the build problems that are blocking #125 
Here's what I've done:
- some cs fix
- fixed php 5.5 build (which is available only with `dist: trusty` on travis)
- removed some deprecation from `.travis.yml` just to keep it up to date
- forced HHVM to 3.30 version, which will be [the last one supporting PHP](https://hhvm.com/blog/2018/09/12/end-of-php-support-future-of-hack.html)
- forced the use of phpunit 5.7 with hhvm as it's [incompatible with phpunit 7](https://docs.travis-ci.com/user/languages/php/#hhvm-versions-are-available-on-trusty-only)
I hope this will be useful
=> Fixes build for old php version and hhvm

src/Generator/BooleanGenerator.php, test/Generator/BooleanGeneratorTest.php
The `\Eris\Generator\BooleanGenerator::shrink` method currently returns
the unboxed value `false`.
This PR makes the return value a `\Eris\Generator\GeneratedValueSingle` matching the `\Eris\Generator::shrink` signature.
This PR is a backward compatibility breaking bugfix.
Related test: `\Eris\Generator\BooleanGeneratorTest::testShrinksToFalse`
Fixes issue https://github.com/giorgiosironi/eris/issues/123
=> Box BooleanGenerator shrink return value

src/Sample.php, src/TestTrait.php, test/SampleTest.php
This PR doesn't contain any BC breaks, unless someone has overridden `\Eris\Sample` (which is not part of the intended user API as far as I can tell).
Closes https://github.com/giorgiosironi/eris/issues/128
=> Allow specifying the generator size when sampling

src/Generator.php, src/Generator/AssociativeArrayGenerator.php, src/Generator/BindGenerator.php, src/Generator/BooleanGenerator.php, src/Generator/CharacterGenerator.php, src/Generator/ChooseGenerator.php, src/Generator/ConstantGenerator.php, src/Generator/DateGenerator.php, src/Generator/ElementsGenerator.php, src/Generator/FloatGenerator.php, src/Generator/FrequencyGenerator.php, src/Generator/GeneratedValue.php, src/Generator/GeneratedValueOptions.php, src/Generator/IntegerGenerator.php, src/Generator/MapGenerator.php, src/Generator/NamesGenerator.php, src/Generator/OneOfGenerator.php, src/Generator/RegexGenerator.php, src/Generator/SequenceGenerator.php, src/Generator/SetGenerator.php, src/Generator/StringGenerator.php, src/Generator/SubsetGenerator.php, src/Generator/SuchThatGenerator.php, src/Generator/TupleGenerator.php, src/Generator/VectorGenerator.php, test/Generator/BindGeneratorTest.php
Bugfix allowing multiple shrink steps to be executed on generators that return multiple values when used in a bind generator.
A test for the failing scenario is included in the PR in
`\Eris\Generator\BindGeneratorTest::testShrinkBindGeneratorWithCompositeValue`
Both `\Eris\Generator\GeneratedValueOptions` and `\Eris\Generator\GeneratedValueSingle` implement the interface `\Eris\Generator\GeneratedValue`.  
Until now `GeneratedValue` was only a marker interface without any methods.  
This PR adds the public methods shared by `GeneratedValueSingle` and `GeneratedValueOptions` to the interface, and changes the argument type of `public function shrink;` to `\Eris\Generator\GeneratedValue`.
New `GeneratedValue` methods:  
* `public function map(callable $applyToValue, $generatorName);`
* …
=> Allow shrink() to receive GeneratedValueOptions

src/Generator/SubsetGenerator.php, test/Generator/StringGeneratorTest.php
This PR fixes two instances of curly bracers used for array and/or string index access. This has been deprecated in PHP 7.4:
see https://wiki.php.net/rfc/deprecate_curly_braces_array_access
=> fix for PHP 7.4 string index access

src/TestTrait.php
Badly-formatted @param in docblock for Eris\TestTrait::limitTo (see https://psalm.dev/008) corrected
=> Corrected Invalid Docblock

src/Quantifier/ForAll.php
When using Eris, the missing implementation of the "when" and "and" methods gets flagged by static analyzers.
To overcome this issue i implemented the "when" method as an alias to "__invoke" and additionally annotaded the "and" method in the class-level docblock, as certain reserved key-words cannot be used as method names in PHP 5.
=> Added "when" method alias. Annotated "and" method.

src/Facade.php, src/TestTrait.php
PHPUnit had an internal method getAnnotations which was removed in latest version.
This change avoids uses php unit's supported methods
to fetch annotations so that the library can work with latest
versions of phpunit
Relates to #142
=> Replaces usage of unsupported internal method

.github/workflows/ci.yml, .gitignore, CHANGELOG.md, Makefile, README.md, composer.json, docker-compose.yml, rector.php, test/Generator/BindGeneratorTest.php
Also
- drop support for old versions of PHPUnit
- configure and run Rector for refactoring
=> Drop support for PHP < 7.4, PHPUnit < 8

docs/shrinking.rst
The shrinking time limit example points to incorrect file. Made me a bit confused while reading the documentation.
=> Fix shrinking time limit example file reference

.github/workflows/ci.yml, README.md, phpstan-baseline.neon, psalm-baseline.xml, src/Generator/SuchThatGenerator.php, src/TestTrait.php, test/ExampleEnd2EndTest.php, test/Generator/NamesGeneratorTest.php, test/Generator/RegexGeneratorTest.php, test/Generator/TupleGeneratorTest.php, test/PHPUnitCommandTest.php, test/Quantifier/SizeTest.php, test/Random/MersenneTwisterTest.php, test/Shrinker/MultipleTest.php
Fix #174
Opening this pull request to solve deprecations happening with PHPUnit 11, such as `Metadata found in doc-comment for method SomeClass::erisSetup(). Metadata in doc-comments is deprecated and will no longer be supported in PHPUnit 12. Update your test code to use attributes instead.`
- Convert `@before` and `@beforeClass` annotations to attributes
- Update the README.md too.
- Update PHPStan baseline, to solve PHPStan errors
- Solve own test deprecations (mostly linked to the `@DataProvider` annotation)
- Update test matrix to account for PHPUnit11 and PHP8.3
=> chore: Promote annotations @before and @beforeClass to attributes
